# Generated by Django 4.1.3 on 2023-03-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_descrip', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
