# Generated by Django 4.1.3 on 2023-05-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='desc',
            new_name='Cdesc',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='image',
            new_name='Cimage',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='Cprice',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='Cprod_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_name',
            new_name='Cprod_name',
        ),
    ]
