# Generated by Django 4.1.3 on 2023-07-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart_cquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Cquantity',
        ),
    ]
