# Generated by Django 4.1.3 on 2023-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cart_cquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Cquantity',
            field=models.IntegerField(),
        ),
    ]
